default_view_test:
  view: yes
  icon: mdi:home
  name: home test
  entities:
    - group.modes
    - group.sensors_interior
    - group.sensors_current_weather_1
    - weather.weather_hourly
    - weather.weather_daily
    - group.heaters
    - group.bedroom_cover
    - group.media
    - group.xiaomi
    - group.washer
    - group.window_sensors
    - group.lights_living_room

modes:
  name: Modes
  entities:
    - input_boolean.summer_mode
    - input_boolean.winter_mode

media_view:
  view: yes
  icon: mdi:television-classic
  entities:
    - group.media

weather:
  view: yes
  icon: mdi:weather-cloudy
  entities:
    - weather.weather_hourly
    - weather.weather_daily
    - group.sensors_current_weather_1
    - group.sensors_current_weather_2
    - group.sensors_weather_forecast_1_day
    - group.sensors_weather_forecast_2_day
    - group.sensors_weather_forecast_3_day

sensors_interior:
  name: Sensors Interior
  entities:
    - sun.sun
    - sensor.air_quality_livingroom
    - sensor.humidity_livingroom
    - sensor.temp_livingroom

washer:
  name: washer
  entities:
    - sensor.washer
    - switch.switch_washer

heaters_view:
  view: yes
  name: heaters view
  icon: mdi:radiator
  entities:
    - group.heaters
    - group.heaters_automations

heaters:
  name: Heaters
  entities:
    - input_select.all_heaters
    - input_select.heater_living_room
    - input_select.heater_kitchen
    - input_boolean.disable_automation_heater_office
    - input_select.heater_office
    - input_select.heater_bedroom

heaters_automations:
  name: Heaters automations
  entities:
    - automation.bedroom_morning_confort
    - automation.bedroom_morning_back_eco
    - automation.bedroom_evening_confort
    - automation.living_morning_confort
    - automation.living_morning_back_eco
    - automation.living_evening_confort
    - automation.living_morning_confort_allday
    - automation.kitchen_morning_confort
    - automation.kitchen_morning_back_eco
    - automation.kitchen_evening_confort
    - automation.kitchen_evening_eco
    - automation.kitchen_lunch_confort
    - automation.kitchen_lunch_back_eco
    - automation.office_evening_confort
    - automation.office_morning_confort_allday
    - automation.out_heaters_eco
    - automation.out_heaters_back
    - automation.heaters_night
    - automation.heater_office_night

media:
  name: Media Center
  icon: mdi:television-classic
  entities:
    - media_player.kodi
    - media_player.yamaha
    - media_player.tv

xiaomi:
  name: xiaomi
  entities:
    - input_boolean.automation_vacuum
    - vacuum.vacuum_up
    - vacuum.vacuum_down
    - fan.xiaomi_miio_device

automation_view:
  name: Automation
  icon: mdi:robot
  view: yes
  entities:
    - group.all_automations
    - group.all_scripts

view_all:
  view: yes
  icon: mdi:alert
  name: All devices
  entities:
    - group.all_switches
    - group.all_lights
    - group.all_devices
    - group.all_scripts
    - group.all_automations
    - group.all_fans
    - group.all_vacuum_cleaners
    - group.calendar
    - group.media