- platform: yr
  name: Current weather
  monitored_conditions:
    - temperature
    - symbol
    - precipitation
    - windSpeed
    - pressure
    - windDirection
    - humidity
- platform: darksky
  api_key: !secret darksky_api_key
  name: Weather forecast
  monitored_conditions:
    - summary
    - temperature
    - apparent_temperature
    - humidity
    - precip_probability
    - precip_intensity
    - wind_speed
    - wind_bearing
    - pressure
  forecast:
    - 1
    - 2
    - 3
  update_interval:
    minutes: 10