- platform: template
  covers:
    bedroom_cover:
      friendly_name: "Bedroom Cover"
      position_template: "{{ (((states.input_number.window_position.state | int) * 100)/27 | int) }}"
      open_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power2'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power1'
            payload: 'ON'
      close_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power1'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power2'
            payload: 'ON'
      stop_cover:
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power1'
            payload: 'OFF'
        - service: mqtt.publish
          data:
            topic: 'cmnd/sonoff_cover_bedroom/power2'
            payload: 'OFF' 